### ISSUE TITLE
More info about the training

### ISSUE THREAD

**Issue by Kruk2** [Sir-Prise/ahegao-detector#1]
Hi!
Could you share more information about the model?
Could you share your training dataset?

**Comment by Sir-Prise** [comment]
I got most of the training data by downloading ahegao compilations from YouTube, extracting frames, extracting faces and then manually classifying the pictures.

You can download it here: https://mega.nz/file/KrRWgRhT#fRc2wj0qAUreWrC-tZbgF84ADkF0Nb__CphkzYYkk5Q

This is my first AI experiment, so the layers are just based on a tutorial and I wasn't able to get better results, so I don't post it as it will probably just confuse you :D
